---
kind: pipeline
name: build

trigger:
  branch:
  - master

clone:
  disable: true

steps:
- name: clone
  pull: if-not-exists
  image: plugins/git
  when:
    event:
    - pull_request
    status:
    - success

- name: test
  image: elixir:1.7-alpine
  commands:
  - apk add --update bash openssl git
  - mix local.hex --force && mix local.rebar --force
  - mix deps.get
  - mix compile --warnings-as-errors
  - mix test
  when:
    event:
    - pull_request
    status:
    - success

- name: notify
  pull: if-not-exists
  image: resuelve/drone-fish
  environment:
    GOOGLE_CHAT_URL:
      from_secret: google_chat_url
  when:
    event:
    - pull_request
    status:
    - success
    - failure

---
kind: pipeline
name: publish

trigger:
  event:
  - tag

clone:
  disable: true

steps:
- name: clone
  pull: if-not-exists
  image: plugins/git
  when:
    status:
    - success

- name: publish
  image: elixir:1.7-alpine
  commands:
  - apk add --update bash openssl git
  - mix local.hex --force && mix local.rebar --force
  - mix deps.get
  - mix compile --warnings-as-errors
  - HEX_API_KEY=$HEX_KEY mix hex.publish --yes
  environment:
    HEX_KEY:
      from_secret: hex_key
  when:
    status:
    - success

- name: notify
  pull: if-not-exists
  image: resuelve/drone-fish
  environment:
    GOOGLE_CHAT_URL:
      from_secret: google_chat_url
  when:
    status:
    - success
    - failure

... 
